/*
 * Copyright 2026 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.example.chatapp.data

import android.net.Uri
import com.example.chatapp.uicomponents.DisplayMessage
import dagger.Binds
import dagger.Module
import dagger.hilt.InstallIn
import dagger.hilt.components.SingletonComponent
import kotlinx.coroutines.delay
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.map
import kotlinx.coroutines.flow.update
import java.util.UUID
import javax.inject.Inject
import javax.inject.Singleton
import kotlin.random.Random
import kotlin.time.Duration.Companion.milliseconds

/**
 * Repository for managing message-related operations, such as sending messages to users or bots.
 */
interface MessageRepository {
    /**
     * Retrieves messages for a specific recipient.
     */
    fun getMessages(recipientId: String): Flow<List<DisplayMessage>>

    /**
     * Saves a message to the in-memory store.
     */
    fun saveMessage(
        recipientId: String,
        message: DisplayMessage,
    )

    /**
     * Sends a message to the specified recipients.
     *
     * @param text The content of the message to be sent.
     * @param recipientIds A list of unique identifiers for the message recipients.
     * @param imageUris An optional list of URIs for images to be sent with the message.
     * @return A unique identifier for the sent message.
     */
    suspend fun send(
        text: String,
        recipientIds: List<String>,
        imageUris: List<String>? = null,
    ): String

    /**
     * Sends a message to a simulated bot and returns its response.
     *
     * @param text The message content to send to the bot.
     * @return The response text generated by the bot.
     */
    suspend fun sendToBot(text: String): String
}

@Singleton
class MessageRepositoryImpl
    @Inject
    constructor() : MessageRepository {
        // Used for message delays.
        private val random = Random(System.currentTimeMillis())

        // In-memory store for messages: Map of Recipient ID to their messages
        private val inMemoryMessages = MutableStateFlow<Map<String, List<DisplayMessage>>>(emptyMap())

        override fun getMessages(recipientId: String): Flow<List<DisplayMessage>> {
            return inMemoryMessages.map { it[recipientId] ?: emptyList() }
        }

        override fun saveMessage(
            recipientId: String,
            message: DisplayMessage,
        ) {
            inMemoryMessages.update { currentMap ->
                val currentMessages = currentMap[recipientId] ?: emptyList()
                // Append at the beginning because the UI might be observing it that way,
                // or end depending on UI. Existing code appends at the beginning:
                // listOf(newMessage) + it.messages
                val updatedMessages = listOf(message) + currentMessages
                currentMap + (recipientId to updatedMessages)
            }
        }

        /** Random delay to simulate network. */
        suspend fun randomDelay(maxDelay: Long = 1000) = delay(random.nextLong(maxDelay).milliseconds)

        override suspend fun send(
            text: String,
            recipientIds: List<String>,
            imageUris: List<String>?,
        ): String {
            // Simulate network delay
            randomDelay()
            val sentAt = System.currentTimeMillis()

            recipientIds.forEach { id ->
                saveMessage(
                    id,
                    DisplayMessage(
                        content = text,
                        sentAt = sentAt,
                        isInbound = false,
                        senderName = "Me",
                        images = imageUris?.map { Uri.parse(it) } ?: emptyList(),
                    ),
                )
            }
            return UUID.randomUUID().toString()
        }

        override suspend fun sendToBot(text: String): String {
            // Simulate network delay
            randomDelay()
            val responses =
                listOf(
                    "Hi there! What's on your mind today?",
                    "I'd love to hear more about your perspective on this.",
                    "I don't have personal experiences, but I'm ready to listen!",
                    "Could you give me an example of what you mean?",
                    "Makes perfect sense!",
                    "Welcome! What are we working on right now?",
                    "That sounds like a fascinating topic to explore.",
                    "I'm here whenever you're ready to start.",
                    "Could you break that down a bit further for me?",
                    "Got it. Let's dive in!",
                )
            return responses[Random.nextInt(responses.size)]
        }
    }

@Module
@InstallIn(SingletonComponent::class)
abstract class MessageModule {
    @Binds
    abstract fun bindMessageRepository(impl: MessageRepositoryImpl): MessageRepository
}
